routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NotaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/notas');

//    return view('welcome');
//Route::post('/notas/results', [NotaController::class, 'search'])->name('notas.results');
Route::get('/notas/search', [NotaController::class, 'search'])->name('notas.search');
Route::post('/notas/results', [NotaController::class, 'results'])->name('notas.results');
Route::resource('/notas','App\Http\Controllers\NotaController');

app/Models/Nota.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Nota extends Model
{
    use HasFactory;
	protected $fillable = ['pchave', 'descrição', 'conteúdo'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/NotaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateNotaRequest;
use App\Http\Requests\EditNotaRequest;
use App\Models\Nota;
use Illuminate\Http\Request;

class NotaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	$notas = Nota::paginate(5);
	return view('notas.index', compact('notas'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
	return view('notas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
	Nota::create ([
		'pchave' => $request->pchave,
		'descrição' => $request->descrição,
		'conteúdo' => $request->conteúdo
]);
	flash("Anotação realizada com sucesso!");
	return redirect()->route('notas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Nota  $nota
     * @return \Illuminate\Http\Response
     */
    public function show(Nota $nota)
    {
        //
	return view('notas.show', compact('nota'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Nota  $nota
     * @return \Illuminate\Http\Response
     */
    public function edit(Nota $nota)
    {
        //
		return view('notas.edit', compact('nota'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Nota  $nota
     * @return \Illuminate\Http\Response
     */
    public function update(EditNotaRequest $request, Nota $nota)
    {
        //
$nota->update([
            'pchave' => $request->pchave,
            'descrição' => $request->descrição,
	    'conteúdo' => $request->conteúdo
        ]);
        flash("Anotação atualizada com sucesso!");
        return redirect()->route('notas.index');
    }

    public function search()
	    {
		return view('notas.search');
	    }


    public function results (Request $request)
	    {
		$pchave = $request->input('pchave');
//		$notas = Nota::where('pchave', $pchave)->first();
		$nota = Nota::where('pchave', $pchave)->first();
/**
		foreach ($notas as $item)
			{
				if($item->pchave = $pchave)
				{
//				dd($nota->pchave);
				$nota = $item;
				}
			}
**/
		if(isset($nota))
			{
			return view('notas.show', compact('nota'));
			}
		else
			{
			flash('Palavra não cadastrada!');
			return redirect()->route('notas.search');
			}
	    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Nota  $nota
     * @return \Illuminate\Http\Response
     */
    public function destroy(Nota $nota)
    {
        //
	$nota->delete();
        flash("Anotação excluída!");
        return redirect()->back();
    }
}

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', env('APP_NAME'))</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<div class="container my-5">
    @include('flash::message')
    @yield('content')
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script>
    $('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script>
</body>
</html>

resources/views/notas/create.blade.php
@extends('layouts.master')

@section('title') Criando nova anotação @endsection

@section('content')
<br><a href="http://www.brdsoft.com.br"><img src="/logo-azul-com-texto.png"style="width:120px;height:60px;"></a><br>
    <form action="{{ route('notas.store') }}" method="post">
        @csrf
        <div class="card card-default">
            <div class="card-header">
                Criando anotação
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="pchave">Palavra chave</label>
                    <input type="text" class="form-control @if($errors->has('pchave')) is-invalid @endif" name="pchave" value="{{ old('pchave') }}">
                    @if($errors->has('pchave'))
                        <div class="invalid-feedback">{{ $errors->first('pchave') }}</div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="descrição">Descrição</label>
                    <textarea cols="5" rows="3" class="form-control @if($errors->has('descrição')) is-invalid @endif" name="descrição">{{ ('descrição') }}</textarea>
                    @if($errors->has('description'))
                        <div class="invalid-feedback">{{ $errors->first('descrição') }}</div>
                    @endif
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group">
                    <label for="conteúdo">Conteúdo</label>
                    <textarea cols="5" rows="14" class="form-control @if($errors->has('conteúdo')) is-invalid @endif" name="conteúdo">{{ ('conteúdo') }}</textarea>
                    @if($errors->has('conteúdo'))
                        <div class="invalid-feedback">{{ $errors->first('conteúdo') }}</div>
                    @endif
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Salvar</button>
                <a href="{{ route('notas.index') }}" class="btn btn-default">Cancelar</a>
            </div>
        </div>
    </form>
@endsection

resources/views/notas/edit.blade.php
@extends('layouts.master')

@section('title') Editar anotação @endsection
<br><a href="http://www.brdsoft.com.br"><img src="/logo-azul-com-texto.png"style="width:120px;height:60px;"></a><br>
@section('content')
    <form action="{{ route('notas.update', $nota->id) }}" method="post">
        @csrf
        @method('PUT')
        <div class="card card-default">
            <div class="card-header">
                Editar anotação
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="pchave">Palavra chave</label>
                    <input type="text" class="form-control @if($errors->has('pchave')) is-invalid @endif" name="pchave"
                           value="{{ $nota->pchave }}">
                    @if($errors->has('pchave'))
                        <div class="invalid-feedback">{{ $errors->first('pchave') }}</div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="descrição">Descrição</label>
                    <textarea cols="5" rows="8" class="form-control @if($errors->has('descrição')) is-invalid @endif"
                              name="descrição">{{ $nota->descrição }}</textarea>
                    @if($errors->has('conteúdo'))
                        <div class="invalid-feedback">{{ $errors->first('descrição') }}</div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="conteúdo">Conteúdo</label>
                    <textarea cols="5" rows="16" class="form-control @if($errors->has('conteúdo')) is-invalid @endif"
                              name="conteúdo">{{ $nota->conteúdo }}</textarea>
                    @if($errors->has('conteúdo'))
                        <div class="invalid-feedback">{{ $errors->first('conteúdo') }}</div>
                    @endif
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Atualizar</button>
                <a href="{{ route('notas.index') }}" class="btn btn-default">Cancelar</a>
            </div>
        </div>
    </form>
@endsection

resources/views/notas/index.blade.php
@extends('layouts.master')

@section('title') Anotações old black web @endsection

@section('content')
<br><a href="http://www.brdsoft.com.br"><img src="/logo-azul-com-texto.png"style="width:240px;height:120px;"></a><br>
<h3>Old black web</h3>
<p>Sistema para anotações e apontamentos.</p>
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('notas.create') }}" class="btn btn-primary pull-right mb-3">Nova anotação</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="notas/search" class="btn btn-primary pull-right mb-3">Procurar anotação</a>
	</div>
    </div>
  
  <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Palavra chave</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @forelse($notas as $nota)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $nota->pchave }}</td>
                    <td>{{ $nota->descrição }}</td>
                    <td>
                            <a href="{{ route('notas.edit', $nota->id) }}" type="button" class="btn btn-primary"><i class="fa fa-edit"></i></a>

                            <a href="{{ route('notas.show', $nota->id) }}" type="button" class="btn btn-info"><i class="fa fa-eye"></i></a>

                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete_nota_{{ $nota->id }}">
                                <i class="fa fa-trash"></i>
                            </button>

   <div class="modal fade" id="delete_nota_{{ $nota->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <form action="{{ route('notas.destroy', $nota->id) }}" id="form_delete_nota_{{ $nota->id }}" method="post">
                                        @csrf
                                        @method('DELETE');
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confirmar exclusão</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Quer mesmo excluir "<b>{{ $nota->pchave }}</b>" das anotações?
                                            </div>
						<div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                                                <button type="submit" class="btn btn-danger">Sim excluir anotação!</button>
                                            </div>
					</div>
                                    </form>
                                </div>
                            </div>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" align="center">Nenhuma anoptação encontrada.</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>
    <div class="row">
        {{ $notas->links() }}
    </div>
@endsection

resources/views/notas/search.blade.php
@extends('layouts.master')

@section('title') Anotações old black web @endsection
@section('content')
<br><a href="http://www.brdsoft.com.br"><img src="/logo-azul-com-texto.png"style="width:120px;height:60px;"></a><br>
  <form method="post" action="{{ route ('notas.results') }}">
        @csrf
        @method('POST')
        <div class="card card-default">
            <div class="card-header">
                Pesquisar anotações
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="pchave">Palavra chave</label>
                    <input type="input" class="form-contro"l  name="pchave">
                </div>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Pesquisar</button>
            </div>
        	    <a href="{{ route('notas.index') }}" class="btn btn-info pull-right mb-3">Voltar</a>
	        </div>
	    </form>
@endsection

resources/views/notas/show.blade.php
@extends('layouts.master')

@section('title') Ver anoração @endsection
<br><a href="http://www.brdsoft.com.br"><img src="/logo-azul-com-texto.png"style="width:120px;height:60px;"></a><br>
@section('content')
    <div class="row">
        <div class="col-md-12">
            <a href="{{ route('notas.index') }}" class="btn btn-info pull-right mb-3">Voltar</a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <tr>
                <th>Palavra chave</th>
                <td>{{ $nota->pchave }}</td>
            </tr>
            <tr>
                <th>Descrição</th>
                <td>{{ $nota->descrição }}</td>
            </tr>
            <tr>
                <th>Conteúdo</th>
                <td>{{ $nota->conteúdo }}</td>
            </tr>
        </table>
    </div>
@endsection